import { useEffect, useState } from 'react'
import { generateOutfits } from '../api/stylistApi'
import BackLink from '../components/BackLink'
import { useToast } from '../components/ToastProvider'

export default function RecommendedOutfitsPage({ onBack, onVisualize }) {
  const notify = useToast()
  const [outfits, setOutfits] = useState([])
  const [loading, setLoading] = useState(true)

  const load = () => {
    setLoading(true)
    generateOutfits().then((data) => {
      setOutfits(data)
      setLoading(false)
    })
  }

  useEffect(load, [])

  return (
    <div className="max-w-6xl mx-auto px-6 py-14">
      <BackLink onClick={onBack} />

      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-bold mb-1">Recommended Outfits</h1>
          <p className="text-sm text-soft">Generated by AI Stylist based on your wardrobe</p>
        </div>
        <button onClick={load} className="btn-primary">
          Generate Again
        </button>
      </div>

      {loading ? (
        <p className="eyebrow text-center py-16">Generating outfits...</p>
      ) : (
        <div className="grid md:grid-cols-2 gap-6">
          {outfits.map((outfit) => (
            <div key={outfit.id} className="panel p-5">
              <div className="placeholder-box aspect-video w-full mb-4">Outfit {outfit.number} Preview</div>
              <div className="flex items-start justify-between mb-2">
                <h3 className="font-semibold">{outfit.title}</h3>
                <span className="eyebrow">#{outfit.number}</span>
              </div>
              <p className="eyebrow mb-1.5">Items Included</p>
              <ul className="text-sm text-soft mb-3 space-y-0.5">
                {outfit.items.map((item) => (
                  <li key={item}>• {item}</li>
                ))}
              </ul>
              <div className="flex flex-wrap gap-1.5 mb-3">
                {outfit.tags.map((tag) => (
                  <span key={tag} className="tag">
                    {tag}
                  </span>
                ))}
              </div>
              <p className="text-sm text-soft mb-4">{outfit.description}</p>
              <div className="flex gap-2.5">
                <button onClick={() => onVisualize(outfit)} className="btn-outline flex-1">
                  Visualize
                </button>
                <button onClick={() => notify(`"${outfit.title}" saved to your outfits`)} className="btn-primary flex-1">
                  Save Outfit
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
