/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StylistRouteImport } from './routes/stylist'
import { Route as TryonRouteImport } from './routes/tryon'
import { Route as WardrobeRouteImport } from './routes/wardrobe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistRoute = StylistRouteImport.update({
  id: '/stylist',
  path: '/stylist',
  getParentRoute: () => rootRouteImport,
} as any)
const TryonRoute = TryonRouteImport.update({
  id: '/tryon',
  path: '/tryon',
  getParentRoute: () => rootRouteImport,
} as any)
const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/studio': typeof StudioRoute
  '/stylist': typeof StylistRoute
  '/tryon': typeof TryonRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/studio': typeof StudioRoute
  '/stylist': typeof StylistRoute
  '/tryon': typeof TryonRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/studio': typeof StudioRoute
  '/stylist': typeof StylistRoute
  '/tryon': typeof TryonRoute
  '/wardrobe': typeof WardrobeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/studio'
    | '/stylist'
    | '/tryon'
    | '/wardrobe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/studio'
    | '/stylist'
    | '/tryon'
    | '/wardrobe'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/studio'
    | '/stylist'
    | '/tryon'
    | '/wardrobe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  StudioRoute: typeof StudioRoute
  StylistRoute: typeof StylistRoute
  TryonRoute: typeof TryonRoute
  WardrobeRoute: typeof WardrobeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylist': {
      id: '/stylist'
      path: '/stylist'
      fullPath: '/stylist'
      preLoaderRoute: typeof StylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tryon': {
      id: '/tryon'
      path: '/tryon'
      fullPath: '/tryon'
      preLoaderRoute: typeof TryonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  StudioRoute: StudioRoute,
  StylistRoute: StylistRoute,
  TryonRoute: TryonRoute,
  WardrobeRoute: WardrobeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
